### ISSUE TITLE
Question for UFine6926 and UFine3C

### ISSUE THREAD

**Issue by BIGBALLON** [Zplusdragon/UFineBench#1]
Hi, @Zplusdragon , thanks for your great work UFineBench, I have two questions I would like to ask

- When will UFineBench be released?
- there is a Granularity Queries Q during the training process and how this Queries is generated.

![image](https://github.com/Zplusdragon/UFineBench/assets/7837172/0446033e-2682-414e-82bb-c8105ef124ab)

thanks again!

**Comment by Zplusdragon** [comment]
Thanks for your attention. 
1. UFine6926 and UFine3C will be released this week. (Tuesday soonest) 
2. Q is some learnable query tokens which are randomly initialized.
Please pay attention to subsequent updates in time.

**Comment by MeiZaL** [comment]
Could you provide the download link for the Ufine6926 dataset? I have sent an email to the author but have not received a reply.

**Comment by Zplusdragon** [comment]
Please resend the relevant application materials to the email address jlongzuo@hust.edu.cn. I usually respond on the same day or the next day. If you do not receive a response, it may be due to an oversight on my part. I apologize for any inconvenience this may cause.
