### ISSUE TITLE
Question about the new metric mSD

### ISSUE THREAD

**Issue by morgenzhang** [Zplusdragon/UFineBench#2]
Thanks for your work!  I have one question regarding the new released metric. 
According to the description in the paper, the calculation process of _Similarity Distribution_ can be divided into two sub-parts: PNR and ASP. I try to reproduce the results of the toy examples, e.g. rank list 1, as the following steps:
1) PNR = 1 - exp(-x), s.t. x = (0.81/0.79 + 0.81/0.76 + 0.81/0.75 + 0.77/0.79 + 0.77/0.76 + 0.77/0.75) / 6 and finally obtain PNR=0.6433;
2) ASP = (0.81/0.81 + (0.81 + 0.77)/(0.81 + 0.79 + 0.77)) / 2 and get ASP=0.8333.
As a result, the SD metric value of rank list 1 will be 0.6433*0.8333=0.5361 which is exactly equal to your proposed result.
However, when I apply the same pipeline to the rest 2 examples, I get wrong SD value 0.8218 and 0.7958 respectively. Since no pesudo-code is available in the paper, I could have misunderstood your idea. It would be appreciated if you can point out my mistake.

**Comment by Zplusdragon** [comment]
It may be that the statement in the paper is not clear enough, which leads to a misunderstanding of the process of calculating PNR. The calculation process of Similarity Distribution for rank list 2 is as the following steps:
1. PNR = 1- exp(-x), s.t. x = ((0.81 + 0.77)/2) / ((0.79+0.15+0.12)/3) and finally obtain PNR=0.8931;
2. ASP = (0.81/0.81 + (0.81+0.77)/(0.81+0.79+0.77)) / 2 and get ASP=0.8333.
As a result, the SD of rank list 2 will be 0.8931*0.8333 = 0.7442 which is exactly equal to the proposed result.
Thanks for your attention. The code for the metric will be released this afternoon!

**Comment by morgenzhang** [comment]
Thanks and now it makes sense. Good news! Looking forward to your new released scripts.
