### ISSUE TITLE
Question about text length

### ISSUE THREAD

**Issue by biburger** [Zplusdragon/UFineBench#3]
Thanks for your work!
You mentioned that the word count for UFine6929 is centered around 80 and used a CLIP text encoder to get text embeddings. I am wondering how you processed prompts longer than 77 words, given that the CLIP text encoder can only take a maximum length of 77 words.

**Comment by shams2023** [comment]
> 感谢您的工作！ 您提到 UFine6929 的字数以 80 左右为中心，并使用 CLIP 文本编码器来获取文本嵌入。我想知道您如何处理超过 77 个单词的提示，因为 CLIP 文本编码器只能接受最大长度 77 个单词。

Is this also what I want to know? How to handle text descriptions with more than 77 words?

**Comment by Zplusdragon** [comment]
When training the models on UFine6926, please interpolate the positional embedding layer of the clip text encoder to 168 tokens.

**Comment by shams2023** [comment]
> When training the models on UFine6926, please interpolate the positional embedding layer of the clip text encoder to 168 tokens.

I have sent you an email hoping to obtain your permission to use your dataset. Looking forward to your reply! Looking forward to using this new dataset!
Thank you for your reply!

**Comment by Zplusdragon** [comment]
The download links have alreardy been sent to your email. Thanks for your attention to our work!

**Comment by shams2023** [comment]
> The download links have alreardy been sent to your email. Thanks for your attention to our work!

thanks!
